# Simulation framework {#sec-sim-framework}

Having defined the theoretical background, it is now time to outline a simulation
framework that fulfills the conditions established above and allows me to study the
hypotheses to be presented in @sec-hyp-def. I use an acceptance loop that is further
developed from the loop described in @kozdoi_et_al_BE_BASL. This section describes
the implementation and justifies the main design decisions.

## Applicants' population {#sec-app-population-simulation}

Recalling Section @sec-measure-theoretic-desc-ri-problem, the applicant population
is determined by the joint distribution of the repayment outcome and the features.
In the simulation, I do not consider latent features (case $f_l = 0$). I first
define a baseline repayment outcome $\tilde{Y} := Y | \{\epsilon = \text{no external effect}\}$
representing the outcome in the absence of an idiosyncratic shock. This variable simplifies
the description of the applicant population and provides the cleanest connection to the distinction
between good and bad applicants as discussed in the last section.

The chosen DGP of $(\tilde{Y}, X)$ is a two-class Gaussian model that specializes to the classical
linear discriminant analysis (LDA) setting through the common-covariance
assumption imposed below. Although this is a deliberately simple DGP, its
well-known statistical properties make it possible to study the RI problem in a
controlled setting.

It holds

$$
\tilde{Y} \sim Bernoulli(\pi_b)
$$ {#eq-Y-tilde-unconditional}

with $\pi_b \in (0,1)$ denoting the probability of a bad applicant. The observable
feature vector $X$^[
    Recall from @eq-X-joint-observable-feats-vec: $X=(X_m^\top,X_h^\top)^\top$.
]
is defined as a Gaussian mixture with two components, a good
one (payers) and a bad one (defaulters). With $o \in \{g,b\}$, the
class-conditional distributions are characterized as

$$
X \mid \{\tilde{Y}=o\}
\sim
\mathcal{N}
\left(
\mu_o
=
\begin{pmatrix}
\mu_{m,o} \\
\mu_{h,o}
\end{pmatrix},
\Sigma_o
=
\begin{pmatrix}
\Sigma_{m,o} & \Sigma_{mh,o} \\
\Sigma_{mh,o}^{\top} & \Sigma_{h,o}
\end{pmatrix}
\right)
$$

with $\Sigma_o$, $\Sigma_{m,o}$, and $\Sigma_{h,o}$ strictly positive definite
(and therefore non-singular). Letting $X_o$ denote $X\mid\{\tilde{Y}=o\}$, I also
use $\phi_{X_o}$ to denote its probability density function. Since $X_o$ is
normally distributed, the density is

$$
\phi_{X_o}(x)
:=
\frac{1}{\sqrt{(2\pi)^f |\Sigma_o|}}
\exp\left\{
    -\frac{1}{2}(x-\mu_o)^\top \Sigma_o^{-1}(x-\mu_o)
\right\}.
$$

For further analysis, it is useful to write down the joint distribution of
$(X,\tilde{Y})$, which corresponds to the marginal distribution of
$\mathbb{P}_{X_m,X_h,X_l,Y}$ over the latent feature component, conditional on
the absence of an idiosyncratic shock. Its density^[
    Following @Pollard_2001 [Ch. 3, Sec. 1], densities are understood in the
    Radon--Nikodym sense with respect to a dominating measure.
]
is defined as the Radon-Nikodym derivative

$$
p_{X,\tilde{Y}}
=
\frac{d\mathbb{P}_{X,\tilde{Y}}}
{d\left(\lambda^f \otimes \#_Y\right)}
$$

where $\#_Y$ denotes the counting measure over $E_Y$. Evaluated pointwise,

$$
p_{X,\tilde{Y}}(x,o)
=
\pi_o \cdot \phi_{X_o}(x)
$$ {#eq-join-density-x-tilde-y}

where $\pi_g := 1-\pi_b$.

From this, the marginals follow directly. The marginal mass function of
$\tilde{Y}$ is

$$
p_{\tilde{Y}}(o)
=
\int_{\mathbb{R}^f}
p_{X,\tilde{Y}}(x,o)\,\lambda^f(dx)
=
\pi_o,
$$ {#eq-marginal-of-Y}

which corresponds to the probability mass function of a Bernoulli distributed
variable. The marginal density of $X$ is

$$
p_X(x)
=
\int_{E_Y}
p_{X,\tilde{Y}}(x,y)\,\#_Y(dy)
=
\pi_b \phi_{X_b}(x)
+
\pi_g \phi_{X_g}(x)
$$ {#eq-marginal-of-X}

and is therefore the density of a Gaussian mixture. Hence,

$$
\mathbb{P}(\tilde{Y}=o \mid X=x)
=
p_{\tilde{Y}\mid X}(o\mid x)
=
\frac{
\phi_{X_o}(x)p_{\tilde{Y}}(o)
}{
p_X(x)
}.
$$ {#eq-posterior-of-Y}

When the class-conditional covariance matrices are equal,
the posterior in @eq-posterior-of-Y has the familiar logistic form. Consequently,
LR is correctly specified for
$\mathbb{P}(\tilde{Y}=b\mid X=x)$ in this setting [@hastie2009elements, Ch. 4].
Under standard regularity conditions, the maximum-likelihood estimator is then
consistent. Since LR is also widely used in practical credit scoring applications,
this provides an additional reason to choose the present DGP.

I next introduce idiosyncratic shocks into the model. As defined from @eq-y-as-measurable-function
onwards, $\epsilon$ indicate whether an idiosyncratic shock occurs and $\varepsilon$ the outcome generated
under a shock. Recall that these variables are independent of $(X,\tilde{Y})$ and from one
another. Both of these RVs are assumed to be Bernoulli distributed with

$$
\mathbb{P}(\epsilon=\text{no shock})
=
\pi_\epsilon
>0
\;\text{ and } \;
\mathbb{P}(\varepsilon=b)
=
\pi_{\varepsilon,b}
\in(0,1).
$$

The resulting posterior probability of a bad outcome is

$$
\mathbb{P}(Y=b\mid X=x)
=
p_{Y=b\mid X}(x)
=
\pi_\epsilon
p_{\tilde{Y}\mid X}(b\mid x)
+
(1-\pi_\epsilon)\pi_{\varepsilon,b}
$$ {#eq-pd-with-shock-perf-bayes}

which defines the Bayes-optimal conditional probability of a bad outcome.

Since the FI does not use $X_h$ when constructing the scorecard, the score
function $s_t$ can only approximate $\mathbb{P}(Y=b\mid X_m=x_m)$.
This distribution can be obtained by integrating out $X_h$. Writing
$x=(x_m^\top,x_h^\top)^\top$, @eq-join-density-x-tilde-y gives

$$
p_{X_m,\tilde{Y}}(x_m,o)
:=
\int_{\mathbb{R}^{f_h}}
p_{X,\tilde{Y}}(x,o)\,
\lambda^{f_h}(dx_h).
$$

Consequently,

$$
X_{m,o}
:=
X_m\mid\tilde{Y}=o
\sim
\mathcal{N}
\left(
\mu_{m,o},
\Sigma_{m,o}
\right)
$$ {#eq-marginal-of-X-m}

and therefore

$$
\mathbb{P}(Y=b\mid X_m=x_m)
=
p_{Y=b\mid X_m}(x_m)
=
\pi_\epsilon
\underbrace{
\frac{
\phi_{X_{m,b}}(x_m)
p_{\tilde{Y}}(b)
}{
p_{X_m}(x_m)
}
}_{=:p_{\tilde{Y}\mid X_m}(b\mid x_m)}
+
(1-\pi_\epsilon)\pi_{\varepsilon,b}
$$ {#eq-pd-with-shock-perf-bayes-reduced-model}

which is the Bayes-optimal conditional probability available to a scorecard
restricted to $X_m$.

For the simulation, I choose a deliberately simple DGP so that its statistical
properties are easy to understand. Specifically, $f_m=2$, $f_h=1$, and 
$\Sigma_g=\Sigma_b=\Sigma$, so that the class-conditional distributions differ only through
their means. This common-covariance specification is the LDA setting used throughout the
simulation. I also set $\pi_\epsilon=1$, so that no idiosyncratic shocks are
considered.^[
    Although this excludes idiosyncratic shocks from the base simulation, the
    mechanism is retained in the general DGP because it provides a useful extension.
    Under symmetric shocks, it would leave the decision boundary unchanged while
    increasing the conditional variance of $Y\mid X$. That would complicate the classification
    problem, but it would be irrelevant to the study of RI as a dynamic problem. Specially
    considering that LR as the scorecard to be used is robust to class outliers
    [@hastie2009elements, Ch. 4]
]
The common covariance matrix is parameterized as

$$
\Sigma(\sigma_{m,12},\sigma_{mh})
=
\Sigma
=
\begin{pmatrix}
1 & \sigma_{m,12} & \sigma_{mh} \\
\sigma_{m,12} & 1 & \sigma_{mh} \\
\sigma_{mh} & \sigma_{mh} & 1
\end{pmatrix}
$$ {#eq-general-form-Sigma}

and the means are given by

```{python}
#| notebook-links: false

from berebasl.simulation.acceptance_loop import generate_initial_and_holdout_population
from inspect import signature

tex_obj_g, _ = dgp_base.good_mixture.univariate_mixture_as_tex("g")
mu_g = tex_obj_g[tex_obj_g.find("\\mu"):tex_obj_g.find(", \\Sigma")]

tex_obj_b, _ = dgp_base.bad_mixture.univariate_mixture_as_tex("b")
mu_b = tex_obj_b[tex_obj_b.find("\\mu"):tex_obj_b.find(", \\Sigma")]

mus_report_str = (
    "$$\n" + mu_b + ", \\; " + mu_g + ".\n$$"
    + " {#eq-mus-chosen}"
)

display(Markdown(mus_report_str))

bayes_err_full_base = dgp_base.bayes_error_under_equal_covs().item()

bayes_err_str = round(bayes_err_full_base * 100, 2)

sigma_m12 = dgp_base.bad_mixture.cov[0,1].item()

sigma_m12_str = f"{sigma_m12:.1f}"

wished_corr_str = f"{wished_corr:.1f}"

min_corr_str = f"{all_corrs.amin().item():.1f}"

max_corr_str = f"{all_corrs.amax().item():.1f}"

n_0, n_1 = base_sim["sample_sizes"][:2].numpy().tolist()

n = n_1 - n_0

q_init = signature(
    generate_initial_and_holdout_population
).parameters["top_percent"].default

n_a_at_0 = int(q_init * n_0)
```

The form in @eq-general-form-Sigma allows to vary the dependence structure
within the chosen standardized covariance parameterization while maintaining
positive definiteness. The admissible values of $\sigma_{m,12}$ and $\sigma_{mh}$
can therefore be selected to study the possible DGPs induced by them.

A useful diagnostic is the performance of the classifiers defined by
@eq-pd-with-shock-perf-bayes and @eq-pd-with-shock-perf-bayes-reduced-model.
These are the Bayes classifiers^[
    Also known as the generative model in the LDA literature.
]
for $Y\mid X$ and $Y\mid X_m$, respectively.
Their theoretical performance is measured by the Bayes error rate, defined as the
probability that the classifier makes an incorrect prediction when classifying as
bad whenever the predicted probability of bad exceeds the predicted probability
of good, and as good otherwise.^[
    This rule does not include a reject-option or abstention class.
]

The Bayes error rate can be calculated analytically using
@eq-bayes-error-rate-formula, as derived in the appendix
(see @sec-derivation-bayes-rate). Let $P_e^*$ denote the error rate of the full
model following @eq-pd-with-shock-perf-bayes, and let $P_e^m$ denote the error
rate of the reduced model following
@eq-pd-with-shock-perf-bayes-reduced-model. In general,

$$
0 \leq P_e^* \leq P_e^m,
$$

and, under the present covariance parameterization, $P_e^m$ does not depend on
$\sigma_{mh}$ because integrating out $X_h$ leaves the marginal distribution of
$X_m$ unchanged. I can therefore examine the Bayes error rates over the complete
admissible region of the covariance parameters, which can be characterized
analytically using @eq-positive-definite-region
(see @sec-set-pos-definite-vcovs in the appendix).

```{python}
#| label: fig-all-bayes-errs
#| fig-cap: "Analysis of Bayes Errors distributions for admissible covariance matrices"

from thesis.helper_scripts.sensitivity_analysis import wrapper_bayes_errors_plot

wrapper_bayes_errors_plot(
    max_corrs=500,
    var_to_hide=base_sim["var_to_hide"],
    vcov=dgp_base.bad_mixture.cov,
    simulated_corrs=base_sim["corr_to_hidden"],
    idx_wished_corr=idx_wished_corr
)
```

In the left panel of @fig-all-bayes-errs we see the heat map of the ratio $P_e^*/P_e^m$.
The graphic shows numerically that

$$
\forall \sigma_{m,12}\;
\exists \sigma_{mh}:
P_e^*=P_e^m.
$$ {#eq-equal-error-rates}

For many of these cases, @eq-equal-error-rates does not imply the Bayes error rate being
zero. As to be disclosed in @sec-the-acceptance-loop, the MNAR mechanism is introduced
through overwrites based on extreme values of $X_h$. Such a mechanism creates
dependence of the acceptance decision on a hidden variable, which would generate an omitted
variable bias when estimating a scorecard based on the model variables. The cases in
@eq-equal-error-rates are useful because they allow to study this MNAR effect
while keeping the achievable Bayes classification error of the reduced model equal
to that of the full model. Thus,
$X_h$ can remain marginally associated with the repayment outcome while providing
essentially no additional discriminatory information for the Bayes classification
boundary once the model features $X_m$ are given.

The joint distribution $(Y,X_m)$ is itself an LDA-type DGP.^[
    This follows from @eq-marginal-of-X-m together with the fact that integrating
    out $X_h$ leaves the common class-conditional covariance structure for $X_m$.
]
Consequently, an appropriately specified LR can consistently estimate through maximum likelihood
its conditional class probability under the usual regularity conditions.

These observations motivate the choice of $\sigma_{m,12}$ for which
@eq-equal-error-rates holds without the Bayes error rates being zero. To study the
effect of the omitted variable, it is useful to choose a value of
$\sigma_{m,12}$ for which the ratio $P_e^*/P_e^m$ varies substantially over the
admissible values of $\sigma_{mh}$. At the same time, $P_e^m$ should remain
sufficiently high that the classification problem is not trivial.

As depicted in the middle panel of @fig-all-bayes-errs, I set
$\sigma_{m, 12} = `{python} sigma_m12`$. I then choose $\sigma_{mh}$ using the right panel.
For the base simulation, I select a value for which the contribution of $X_h$ to the full
Bayes boundary is negligible, namely $\sigma_{mh} = `{python} wished_corr`$. For the base
simulation, this gives $P_e^{*}=P^m_e= `{python} bayes_err_str`\%$. Other values of $\sigma_{mh}$
used later in the sensitivity analysis are selected on an equidistant
grid from `{python} min_corr_str` to `{python} max_corr_str`.

The complete base DGP is visualized in @fig-3d-base-dgp. The Perfect Bayes Boundary
corresponds to the classification boundary of the classifier defined by
@eq-pd-with-shock-perf-bayes. This boundary is derived in the appendix
(see @sec-dec-boundary-perf-bayes-idyiosyncratic-shocks) using the equal covariance.
It can be written as the hyperplane $\mathcal{D}^*$
$$
w^\top x-\beta=\log c
$${#eq-hyperplane-decision-boundary}

with

$$
w=\Sigma^{-1}(\mu_b-\mu_g),
$$

$\beta=w^\top(\mu_b+\mu_g)/2$, and $c>0$ a constant that depends on the
idiosyncratic-shock parameters $\pi_\epsilon$ and $\pi_{\varepsilon,b}$ as well as
the unconditional probability of default $\pi_b$.

```{python}
#| label: fig-3d-base-dgp
#| fig-cap: "Representation of joint distribution $(Y, X)$"

from thesis.helper_scripts.dgp_plotting import (
    extract_dgp_info_for_boundaries,
    plot3d_with_perf_bayes_boundary
)

dgp_info_for_boundaries = extract_dgp_info_for_boundaries(dgp_base)

def sci_tex(x, digits=2):
    s = f"{x:.{digits}e}"
    base, exp = s.split("e")
    exp = int(exp)
    return rf"{base} \cdot 10^{{{exp}}}"

w_xh = dgp_info_for_boundaries["W"][2].item()

w_xh_str = sci_tex(w_xh)

plot3d_with_perf_bayes_boundary(
    dgp_base,
    dgp_info_for_boundaries["W"],
    dgp_info_for_boundaries["bias"]
)
```

Considering the Bayes error rate of the problem and the good separation achieved
by the hyperplane of the Perfect Bayes Boundary visible in
@fig-3d-base-dgp, there is further reason to expect LR to estimate the separation
boundary accurately when all relevant variables are available. To understand how
the problem changes when one variable is omitted, a pairwise component plot such
as @fig-pairwise-base-dgp is useful.

Two decision boundaries are shown there. The first is the projection of
$\mathcal{D}^*$ into a two-dimensional plane, obtained by fixing the component not
shown in the pairwise plot at its unconditional mean. For a component indexed by
$r$, this gives

$$
x\mathtt{[r]} = \mathbb{E}(X | \epsilon = \text{no shock})\mathtt{[r]} = (\pi_b)\mu_b\mathtt{[r]} + (1-\pi_b)\mu_g\mathtt{[r]}.
$$

The second boundary, denoted by $\mathcal{D}^r$, is obtained by integrating out the
non-shown component from the joint distribution and then deriving the corresponding
Bayes decision boundary.

```{python}
#| label: fig-pairwise-base-dgp
#| fig-cap: "Pairwise covariates component representation of $Y, X$"

from thesis.helper_scripts.dgp_plotting import (
    plot_pairwise_dgp_with_perf_bayes_boundaries
)

plot_pairwise_dgp_with_perf_bayes_boundaries(
    dgp_base,
    **dgp_info_for_boundaries
)
```

Through @fig-pairwise-base-dgp, the limited contribution of $X_h$ to the Perfect
Bayes classifier can be visualized. In the left panel, the projected $\mathcal{D}^*$
and $\mathcal{D}^r$ coincide when only $X_m$ is considered. In the middle and right
panels, the projections of $\mathcal{D}^*$ are almost parallel to the $X_h$ axis,
indicating that the full-information Bayes classifier effectively ignores $X_h$.
At the same time, the corresponding $\mathcal{D}^r$ boundaries differ from the
projected full-information boundary. Thus, although the full-information decision
boundary assigns essentially no coefficient to $X_h$, $X_h$ remains marginally
informative about the repayment outcome.

These observations depend only weakly on the exact value used for the projection.
The reason is that the component of the normal vector corresponding to $X_h$ is
numerically zero, namely
<!--`{python} '$' + w_xh_str + '$'` no idea why it does not work--> 
$-2.22 \cdot 10^{-16}$.
The realizations of $X_h$ also almost always lie within the interval $[-6,6]$^[
    This interval comes from a visual inspection of the data, not a proper
    definition of a range where the probability of $X_h$ lying there would be very
    big. However given the class conditional means and the unit variance of $X_h$
    one could expect such a "properly calculated" interval to lie within $[-6,6]$
],
so the contribution of $X_h$ to the classification boundary is negligible. These
properties further clarify the usefulness of the DGP for introducing an MNAR mechanism
based on $X_h$ without simultaneously inducing substantial omitted-variable bias in the
classification boundary.

The pairwise plot also indicates that the classification problem should be well
approximated by LR using only the two model features $X_m$. At the same time, the
plots containing $X_h$ illustrate how its relationship with the model features
changes the marginal separability. In particular, the boundary shown in the panels
containing $X_h$ has a positive slope with respect to $X_{m,1}$ and $X_{m,2}$.
A higher positive correlation between $X_h$ and the model features therefore
increases the separation available when $X_h$ is observed, while a negative
correlation should have the opposite effect.

As a final remark, it is important to make the sampling mechanism of
$\mathbb{P}_{X,Y}$ transparent because the rest of the study is primarily numerical. The
simulation implementation should therefore be open to scrutiny. The sampling
logic is summarized in Algorithm \ref{alg:sampling-x-y}.

First, the realizations of $Y$ are sampled from the Bernoulli distribution defined
in @eq-Y-tilde-unconditional. These labels are then reordered so that observations
from the two classes can be stored in contiguous memory. The corresponding samples
from $X_b$ and $X_g$ are then generated and stacked in the same order as the labels.
This preserves the label-feature correspondence while allowing an efficient
implementation.

\begin{algorithm}
\footnotesize

\caption{Sampling from $\mathbb{P}_{X,Y}$}
\label{alg:sampling-x-y}

\begin{algorithmic}[1]

    \Statex \textbf{Note:} Here the random variables and their realizations are represented with the same notation for convenience

    \Procedure{CreditDGP.sample}{$\sigma_{m,12}, \sigma_{mh}, \pi_b, n$}

        \Statex \textbf{1. Sampling good and bad components} while ensuring contiguous memory per class

        \State
        $\forall i \in \{1, \ldots, n\}: B_i \overset{iid}{\sim} \operatorname{Bernoulli}(\pi_b) \in \{0, 1\}$ with $\mathbb{P}(B_i = 1) = \pi_b$

        \State
        $n_b \gets \sum_{i=1}^n B_i$,
        $n_g \gets n-n_b$

        \State
        $\mathbf{Y}
        \gets
        (\underbrace{b,\ldots,b}_{n_b\text{ times}},
        \underbrace{g,\ldots,g}_{n_g\text{ times}})$

        \Comment{$\mathbf{Y}\in\{b,g\}^n$}

        \Statex \textbf{2. Multivariate Gaussian sampling} for goods and bads

        \State
        $\Sigma_{chol}
        \gets
        \operatorname{CholeskyDecomposition}
        (\Sigma(\sigma_{m,12},\sigma_{mh}))$

        \Comment{See Eq. \ref{eq-general-form-Sigma}}

        \For{$o\in\{b,g\}$}

            \State
            $\mathbf{m}_o
            \gets
            (\mu_o,\ldots,\mu_o)^\top
            \in\mathbb{R}^{n\times f}$

            \State
            $\mathbf{E}
            \gets
            (E_1,\ldots,E_n)^\top$,
            $\forall j\in\{1,\ldots,n\}:
            E_j\overset{iid}{\sim}\mathcal{N}(0_f,I_f)$

            \Statex
            \Comment{Done via i.i.d. sampling of $n\cdot f$ univariate standard normals}

            \State
            $\mathbf{X}_o
            \gets
            \mathbf{m}_o+\mathbf{E}\Sigma_{chol}^{\top}$

        \EndFor

        \State
        $\mathbf{X}
        \gets
        \begin{pmatrix}
        \mathbf{X}_b\\
        \mathbf{X}_g
        \end{pmatrix}$

        \State
        \Return $\mathbf{X},\mathbf{Y}$

    \EndProcedure

\end{algorithmic}

\end{algorithm}


## The acceptance loop {#sec-the-acceptance-loop}

After defining the underlying applicant distribution, the remaining parts of the
DGP can be characterized through the implementation of the acceptance loop.^[
    See @fig-fis-acc-dec-loop for a low-detail overview of the acceptance loop.
]
A detailed representation is given in Algorithm \ref{alg:acceptance-loop}.

The key dynamic feature of the simulation is that applicants in each round are
generated independently from the same underlying DGP. Temporal dependence is
introduced through the acceptance mechanism and the accumulation of accepted
observations used to estimate subsequent scorecards. Thus, the applicant
population itself is stationary, while the observed training population evolves
through repeated selection - as required in the model under Section
@sec-measure-theoretic-desc-ri-problem.

At initialization, the acceptance policy is based on a business rule that is
consistent with the true DGP: higher values of the second component of $X_m$ tend
to indicate good applicants because
$\mu_g[1]>\mu_b[1]$ [@eq-mus-chosen]. After initialization, acceptance is based on
a scorecard and a CV-based decision function.

\begin{algorithm}
\footnotesize

\caption{Acceptance Loop}
\label{alg:acceptance-loop}

\begin{algorithmic}[1]

    \Procedure{AcceptanceLoop}{$\sigma_{m,12}, \sigma_{mh},
    \mathtt{k}, \mathtt{CV}, \texttt{opt\_crit}, p_{\mathtt{bias}}$}

    \Require
    $\sigma_{m,12},\sigma_{mh},\pi_b$ fulfilling the conditions above,
    $p_{\mathtt{bias}}\in[0,1)$

    \Require
    $\texttt{opt\_crit}$ a criterion for calculating the acceptance threshold,
    $\mathtt{k}\geq2$, $\mathtt{CV}\geq1$

        \State $\pi_b \gets 0.5$
        \State
        $\mathtt{DGP}
        \gets
        \mathtt{CreditDGP}
        (\pi_b,\mu_b,\mu_g,\Sigma(\sigma_{m,12},\sigma_{mh}))$

        \Comment{
            See definitions in Eq.~\ref{eq-Y-tilde-unconditional}, \ref{eq-general-form-Sigma}
            and \ref{eq-mus-chosen}
        }

        \State
        $n_i \gets `{python} n_0`,
        f_m \gets 2$,
        $f_h \gets 1$,
        $f \gets f_m+f_h$,
        $n \gets `{python} n`$

        \State
        $\mathbf{X},\mathbf{Y}
        \gets
        \mathtt{DGP.sample}(n=n_i)$

        \Comment{
        $\mathbf{X}\in\mathbb{R}^{n_i\times f}$,
        $\mathbf{Y}\in\{b,g\}^{n_i}$,
        Sampling follows Alg. \ref{alg:sampling-x-y}
        }

        \State
        $q_{\mathtt{init}} \gets `{python} q_init`$

        \State
        \label{al:init-th}
        $\tilde{\tau}_{\mathtt{init}}
        \gets
        \mathtt{quantile}_{1-q_{\mathtt{init}}}
        (\mathbf{X}[:,f_m-1])$

        \Comment{Empirical upper quantile}

        \State
        $\mathbf{Z}
        \gets
        \left(
        a\text{ if }\mathbf{X}[j,f-1]>\tilde{\tau}_{\mathtt{init}}
        \text{ else }r
        \mid
        j \in \{0,\ldots,n_i-1\}
        \right)$

        \Comment{$\mathbf{Z}\in\{a,r\}^{n_i}$}

        \State
        $\mathbf{G}\gets\vec{0}_{n_i}$

        \Comment{$\mathbf{G}\in\mathbb{N}_0^{n_i}$}

        \For{$t\in\{1,\ldots,T\}$}   \Comment{$T=300$ in the experiments}

            \State
            $\mathbf{N}_a
            \gets
            \{j\in\mathbb{N}_0 |
            j<\mathtt{nrows}(\mathbf{X}),
            \mathbf{Z}[j]=a\}$,
            $n_a \gets |\mathbf{N}_a|$

            \State
            $\mathbf{X}_{hist}^{(t)}
            \gets
            \left(
            \mathbf{X}[j,:\!f_m]
            \mid
            j\in\mathbf{N}_a
            \right)$
            \Comment{
            $\mathbf{X}_{hist}^{(t)}\in\mathbb{R}^{n_a\times f_m}$
            }


            \State 
            $\mathbf{Y}_{hist}^{(t)}
            \gets
            \left(
            \mathbf{Y}[j]
            \mid
            j\in\mathbf{N}_a
            \right)$

            \Comment{$\mathbf{Y}_{hist}^{(t)} \in \{b,g\}^{n_a}$}
            

            \State
            \label{al:scorecard-estimation-hist-acc}
            $s_t
            \gets
            \mathtt{trainLR}
            \left(
            \mathbf{X}_{hist}^{(t)},
            \mathbf{Y}_{hist}^{(t)}
            \right)$

            \Comment{LR trained with Newton-Raphson}

            \State
            \label{al:th-at-t}
            $\tau_t
            \gets
            \mathtt{CalcCVThreshold}
            \left(
            \mathbf{X}_{hist}^{(t)},
            \mathbf{Y}_{hist}^{(t)},
            \mathtt{k},
            \mathtt{CV},
            \texttt{opt\_crit}
            \right)$

            \Comment{$\tau_t\in[0,1]$, see Alg. \ref{alg:cv-based-threshold}}

            \State
            $\mathbf{X}_{new}^{(t)},
            \mathbf{Y}_{new}^{(t)}
            \gets
            \mathtt{DGP.sample}(n=n)$

            \State
            \label{al:th-based-d}
            $\mathbf{Z}^{(t)}
            \gets
            (z_0,\ldots,z_{n-1})^\top$,
            where 
            $z_j=a$
            \textbf{if }
            $s_t\left(\mathbf{X}_{new}^{(t)}[j,:\!f_m]\right)<\tau_t$,
            \textbf{else } $z_j=r$

            \If{$p_{\mathtt{bias}}>0$}      \Comment{Apply the MNAR mechanism}

                \State
                $x_b
                \gets
                \mathtt{quantile}_{1-\frac{p_{\mathtt{bias}}}{2}}
                \left(
                \mathbf{X}_{new}^{(t)}[:,f-1]
                \right)$

                \State
                $x_g
                \gets
                \mathtt{quantile}_{\frac{p_{\mathtt{bias}}}{2}}
                \left(
                \mathbf{X}_{new}^{(t)}[:,f-1]
                \right)$

                \State
                \label{al:overwrite-mechanism}
                $\forall j\in\{0,\ldots,n-1\}:
                \mathbf{Z}^{(t)}[j]
                \gets
                \begin{cases}
                a & \mathbf{X}_{new}^{(t)}[j,f-1]<x_g,\\
                r & \mathbf{X}_{new}^{(t)}[j,f-1]>x_b,\\
                z_j & \text{otherwise}.
                \end{cases}$

            \EndIf

            \State
            $\mathbf{X}
            \gets
            \begin{pmatrix}
            \mathbf{X}\\
            \mathbf{X}_{new}^{(t)}
            \end{pmatrix}$,
            
            $\mathbf{Y}
            \gets
            \begin{pmatrix}
            \mathbf{Y}\\
            \mathbf{Y}_{new}^{(t)}
            \end{pmatrix}$,
            
            $\mathbf{Z}
            \gets
            \begin{pmatrix}
            \mathbf{Z}\\
            \mathbf{Z}^{(t)}
            \end{pmatrix}$,
            
            $\mathbf{G}
            \gets
            \begin{pmatrix}
            \mathbf{G}\\
            \vec{t}_n
            \end{pmatrix}$

        \EndFor

    \EndProcedure

\end{algorithmic}

\end{algorithm}


The LR scorecard is selected because, under the equal-covariance Gaussian
specification, its functional form matches the conditional class probability.
Consequently, LR can recover the population decision boundary implied by
$\mathbb{P}(Y=b\mid X_m)$ under correct specification. Therefore, under MAR and usual
regularity conditions LR can be consistently estimated to deliver the necessary
parameters to obtain said decision boundary. The LR scorecard is therefore estimated at line
\ref{al:scorecard-estimation-hist-acc}
using the Newton-Raphson algorithm to maximize the logistic likelihood.

The outcome $Y$ is generally allowed to depend on both $X_m$ and $X_h$. In the
base simulation, however, the effect of $X_h$ on the Bayes classification boundary
is negligible, as shown above, while idiosyncratic shocks are excluded. Thus, in
the absence of MNAR overwrites ($p_{\mathtt{bias}}=0$), the reduced LR model is
correctly specified for the conditional relationship between $Y$ and $X_m$.

The initialization rule is based on $q_{\mathtt{init}}$, so the initial number of
accepted observations is determined by the corresponding empirical upper
quantile, not by $p_{\mathtt{bias}}$. Consequently, when
the initial sample is sufficiently large (which is probably given here as the initial
accepted sample has $n_{\mathtt{i}} \cdot p_{\mathtt{bias}} = `{python} n_a_at_0`$ observations),
the first LR estimate should be close to the population conditional model.

\begin{algorithm}

\footnotesize

\caption{CV-based threshold calculation}
\label{alg:cv-based-threshold}

\begin{algorithmic}[1]

    \Procedure{CalcCVThreshold}{$\mathbf{X},\mathbf{Y},\mathtt{k},
    \mathtt{CV},\texttt{opt\_crit}$}

        \Require
        $\texttt{opt\_crit}\in\{\texttt{ks},\texttt{roc}\}$,
        $\mathbf{X}\in\mathbb{R}^{n\times c}$,
        $\mathbf{Y}\in\{g,b\}^n$

        \State
        $\mathbf{TH}\gets[]$

        \Comment{Buffer for repetition-level thresholds}

        \For{$\mathtt{cv}\in\{1,\ldots,\mathtt{CV}\}$}

            \State
            $\mathbf{TH}_{\mathtt{cv}}\gets[]$

            \Comment{Buffer for fold-level thresholds}

            \State
            $\{
            \mathbf{I}_{tr,1},\ldots,\mathbf{I}_{tr,\mathtt{k}}
            \},
            \{
            \mathbf{I}_{va,1},\ldots,\mathbf{I}_{va,\mathtt{k}}
            \}
            \gets
            \mathtt{CVIndexSet}(n,\mathtt{k})$

            \Statex
            \Comment{
            For all $k$:
            $\mathbf{I}_{tr,k}\cap\mathbf{I}_{va,k}=\emptyset$
            and
            $\bigcup_\kappa \mathbf{I}_{va,\kappa}  = \{0,\ldots,n-1\} = \mathbf{I}_{tr, k} \cup \mathbf{I}_{va, k}$
            }

            \For{$k\in\{1,\ldots,\mathtt{k}\}$}

                \State
                $\mathbf{X}_{tr}
                \gets
                (\mathbf{X}[i]\mid i\in\mathbf{I}_{tr,k})$,
                \quad
                $\mathbf{Y}_{tr}
                \gets
                (\mathbf{Y}[i]\mid i\in\mathbf{I}_{tr,k})$

                \State
                $\mathbf{X}_{va}
                \gets
                (\mathbf{X}[i]\mid i\in\mathbf{I}_{va,k})$,
                \quad
                $\mathbf{Y}_{va}
                \gets
                (\mathbf{Y}[i]\mid i\in\mathbf{I}_{va,k})$

                \If{Less than $4$ observations of each label in the validation or training set}

                    \State
                    \textbf{continue}

                \EndIf

                \State
                $l
                \gets
                \mathtt{trainLR}
                (
                \mathbf{X}_{tr},
                \mathbf{Y}_{tr}
                )$

                \State
                $n_{va}
                \gets
                \mathtt{nrows}(\mathbf{X}_{va})$,
                \quad
                $\mathbf{N}_{va}
                \gets
                \{0,\ldots,n_{va}-1\}$

                \State
                $\mathbf{S}
                \gets
                \mathtt{OrderAscending}
                \{(
                l(\mathbf{X}_{va}[j])
                \mid
                j\in\mathbf{N}_{va}
                )\}$,
                with $\mathbf{Y}_{va}$ reordered accordingly

                \If{$\texttt{opt\_crit}=\texttt{ks}$}

                    \State
                    $\forall o\in\{b,g\},\,i\in\mathbf{N}_{va}$:
                    $F_o[i]
                    \gets
                    \frac{
                    \sum_{j=0}^{i}
                    I(\mathbf{Y}_{va}[j]=o)
                    }{i+1}$

                    \Comment{Empirical class CDFs}

                    \State
                    $i^*
                    \gets
                    \arg\max_{i\in\mathbf{N}_{va}}
                    |F_b[i]-F_g[i]|$

                \Else \Comment{ROC-optimal point}

                    \State
                    $\forall i\in\mathbf{N}_{va}$:
                    $ROC[i]
                    \gets
                    \left(
                    FPR_{\tau=\mathbf{S}[i]},
                    TPR_{\tau=\mathbf{S}[i]}
                    \right)^\top$
                    \Statex \Comment{False Positive Rate and True Positive Rate on $(\mathbf{X}_{va}, \mathbf{Y}_{va})$ if threshold was $\mathbf{S}[i]$}

                    \State
                    $i^*
                    \gets
                    \arg\min_{i\in\mathbf{N}_{va}}
                    \left\|
                    ROC[i]-(0,1)^\top
                    \right\|_2$

                \EndIf

                \State
                $\mathbf{TH}_{\mathtt{cv}}
                \gets
                \operatorname{append}
                (
                \mathbf{TH}_{\mathtt{cv}},
                \mathbf{S}[i^*]
                )$

            \EndFor

            \State
            $\mathbf{TH}
            \gets
            \operatorname{append}
            \left(
            \mathbf{TH},
            \operatorname{ArithmeticMean}
            (\mathbf{TH}_{\mathtt{cv}})
            \right)$

        \EndFor

        \State
        $\tau^*
        \gets
        \operatorname{ArithmeticMean}(\mathbf{TH})$

        \Comment{Returns $\mathtt{na}$ if insufficient labels are available}

        \State
        \Return $\tau^*$

    \EndProcedure

\end{algorithmic}

\end{algorithm}

The decision function therefore has two stages. First, an acceptance threshold is
estimated from the scorecard through repeated $k$-fold cross-validation and a
chosen optimization criterion
(line \ref{al:th-based-d}).
The threshold procedure is summarized in Algorithm
\ref{alg:cv-based-threshold}.

The procedure is intended to stabilize threshold estimates. For each of the $\mathtt{CV}$
repetitions, the accepted historical sample is divided into $k$ training-validation pairs.
An LR model is fitted on each training set, and a threshold is selected on the
corresponding validation set. Two threshold criteria are considered. The first is
the ROC threshold whose point is closest to $(0,1)$ in Euclidean distance (optimal ROc point). The
second is the threshold maximizing the Kolmogorov-Smirnov statistic, namely the
maximum absolute difference between the empirical class CDFs. The thresholds are
then averaged within each repetition and across repetitions.

Both criteria are visualized in @fig-roc-ks-visualization.

```{python}
#| label: fig-roc-ks-visualization
#| fig-cap: "Visualization of criteria for CV-based threshold calculation"
#| out-width: "60%"
#| out-height: "60%"
#| fig-width: 3
#| fig-height: 2

from matplotlib import pyplot as plt
from berebasl.simulation.credit_data_simulation import CreditData
from berebasl.estimation.classifiers import BatchedLogistic
from berebasl.evaluation.batched_metrics import (
    batched_roc_points,
    optimal_roc_thresholds_from_roc_points,
    compute_batched_cdfs_and_sorted
)

at_gen = 60

feats, lbls = base_sim_objs["credit_data"].unbiased_obs(
    up_to_round_idx=at_gen - 1
)

lr = BatchedLogistic(
    n_features=feats.size(-1),
    batch_shape=torch.Size([]),
    dtype=feats.dtype,
    device=feats.device
)

N = feats.size(0)

torch.manual_seed(1807)

rand_perm_N = torch.randperm(N)

count_train = round(N * 0.7)

train_idxs = rand_perm_N[:count_train]

vali_idxs = rand_perm_N[count_train:]

lr.fit(feats[train_idxs], lbls[train_idxs])

scores_vali = lr.predict_prob_bad(
    feats[vali_idxs]
).squeeze(-1)

lbls_vali = lbls[vali_idxs]

figsize_th = (10, 4.1)

fpr, tpr, sorted_scores, sorted_targets, sorted_mask_valid = (
    batched_roc_points(
        scores_vali,
        lbls_vali,
        dim=-1
    )
)

sq_eucl_to_opt = (
    fpr.square() +
    (tpr - 1).square()
)

idx_min_dist = sq_eucl_to_opt.argmin().item()

threshold = round(
    sorted_scores[idx_min_dist].item(),
    2
)

fig, axes = plt.subplots(
    ncols=2,
    figsize=figsize_th
)

ax_roc = axes[0]

ax_roc.plot(
    fpr,
    tpr,
    label="ROC",
    color='C0'
)

ax_roc.scatter(
    fpr[[idx_min_dist]],
    tpr[[idx_min_dist]],
    label=f"ROC-opt. pt. $\\tau={threshold}$",
    s=10,
    zorder=30, color='C1'
)

ax_roc.scatter(
    [0],
    [1],
    label="Best ROC-pt.",
    s=10,
    color='C2',
    zorder=30
)

ax_roc.set_xlabel("False Positive Rate")
ax_roc.set_ylabel("True Positive Rate")
ax_roc.legend()

ax_ks = axes[1]

sorted_scores, sorted_mask, cdf_pos, cdf_neg, sorted_targets = compute_batched_cdfs_and_sorted(
        scores_vali,
        lbls_vali
    )

ks_values = torch.abs(cdf_pos - cdf_neg)

idx_max_ks = ks_values.argmax().item()

ax_ks.plot(
    sorted_scores,
    cdf_pos,
    label="$CDF_b$",
    lw=2, color='C0'
)

ax_ks.plot(
    sorted_scores,
    cdf_neg,
    label="$CDF_g$",
    lw=2, color='C1'
)

x_max_ks = sorted_scores[
    [idx_max_ks, idx_max_ks]
].tolist()

y_max_ks = [
    cdf_pos[idx_max_ks].item(),
    cdf_neg[idx_max_ks].item()
]

ax_ks.plot(
    x_max_ks,
    y_max_ks,
    ls="dashed",
    color='C2',
    lw=2,
    label=f"$\\tau_{{KS}}={round(sorted_scores[idx_max_ks].item(), 2)}$"
)

ax_ks.scatter(
    x_max_ks,
    y_max_ks,
    s=20,
    zorder=30, color='C2'
)

ax_ks.set_xlabel("Probability of Default")
ax_ks.set_ylabel("CDF")
ax_ks.set_title("Kolmogorov-Smirnov criterion")
ax_ks.legend(loc="upper left")

ax_roc.set_title("Optimal ROC point")


plt.show()
```

In the second stage of the decision process, the MNAR mechanism can optionally
be applied. This occurs when $p_{\mathtt{bias}}>0$. The overwrite rule depends on
the tails of the hidden feature $X_h^{(t)}$. More specifically, applicants in the
lower tail are accepted and applicants in the upper tail are rejected, regardless
of the scorecard decision. Because $\mu_g[2]<\mu_b[2]$, the lower tail of $X_h$ is enriched
for good applicants and the upper tail for bad applicants. The overwrite mechanism therefore
tends to accept good applicants and reject bad applicants, while still allowing
overlap between the two classes.

The parameter $p_{\mathtt{bias}}$ controls thereby the total mass assigned to the lower and
upper tails of $X_h$ to which the overwrite rule applies. It is therefore a control
parameter for the strength of the hidden-feature-based selection mechanism, not
necessarily the exact fraction of observations whose original scorecard decisions
are changed. So line
\ref{al:overwrite-mechanism} of Algorithm \ref{alg:acceptance-loop}
should not be understood as a mechanism flipping every decision in for the extreme
values of the hidden factor.

