project:
  type: manuscript

manuscript:
  article: thesis.qmd

# These settings apply to the Python code execution
execute:
  freeze: auto       # Re-runs only if thesis.qmd changed
  echo: false        # Hides code from the PDF (standard for papers)
  warning: false     # Hides python warnings from the PDF
  python: ./../masters_venv/Scripts/python.exe
  results: asis
  notebook-links: false

crossref:
  eq-prefix: "Eq. "

format:
  pdf:
    documentclass: article    # Good for longer works like a thesis
    number-sections: true     # 1, 1.1, 1.1.1
    toc: true                # Table of Contents
    cite-method: biblatex    # Use this for high-quality citations
    biblio-style: apa
    geometry:
      - margin=2.5cm
      - bottom=3cm
    include-in-header: preamble.tex
    fontsize: 12pt
    notebook-links: false
    fig-pos: "H"
    fig-cap-location: bottom
    keep-tex: true
    equation-labels: parenthetical
    lof: true   # List of Figures
    lot: true   # List of Tables
    papersize: a4

# If you want to keep the others just in case:
  html: default
  docx: default
